services:
  - type: web
    name: viofel
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: viofel
          type: web
          property: host
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: viofel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: viofel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: viofel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: viofel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: viofel-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: viofel-db
    plan: free
